### PR TITLE
added prevent-mobile attribute support

### PR DESCRIPTION
**Pull request by Pangolin-**
In reference to #207, added support for a `prevent-mobile` attribute in the directive.

### CODE REVIEW

**Comment by Pangolin-** [comment]
__Usage__:

```
<datepicker prevent-mobile></datepicker>
```

__Purpose__:

Force plugin to use desktop styles, even if on mobile. `<select>` elements are handled inconsistently across mobile devices, so having the option to use the alternate pagination control for month/year selection is useful.

**Comment by robbporto** [comment]
Can we merge this, please?

**Comment by 45kb** [comment]
Hi @Pangolin-

Can you please rename the attribute to `datepicker-mobile=""`

Default true and if false -> your fix.

Let me know, thanks a lot 👍

**Comment by Pangolin-** [comment]
All set @45kb, changes have been pushed.

**Comment by 45kb** [comment]
@Pangolin- commented one line of the code for missing `{}` curly , please add them and we can merge this! thanks for your time, appreciated a lot!

**Comment by Pangolin-** [comment]
@45kb sorry, not sure what you mean, could you elaborate?

**Comment by 45kb** [comment]
@Pangolin- sorry yes , so instead of `if (preventMobile) isMobile = false;` just `if (preventMobile) { isMobile = false; }`

**Comment by Pangolin-** [comment]
Good to go!

**Comment by 45kb** [comment]
thanks @Pangolin- very great job here! Will release it under the next new version.

**Comment by Pangolin-** [comment]
My pleasure mate, cheers.

**Comment by 45kb** [comment]
@robbporto now is available, just update to `2.1.9` 👍

**Comment by robbporto** [comment]
Thanks, @45kb

**Pull request merged**
