### PR TITLE
Ability to change the first day of the week

### PR DESCRIPTION
**Pull request by frsv**
Add function which simple decrement first and last day in month by 1,
so the first day become Monday.

### CODE REVIEW

**Comment by wouldgo** [comment]
Hi,

rough way to change the first day of the week. As far as I saw there is no way to configure this. Maybe some others users need to start them calendar with Sunday. What do you think putting a directive attribute to activate or not this behaviour? @45kb What do you think about?

**Comment by 45kb** [comment]
Hi i appreciated a lot but the PR atm is not valid. Indeed a new attribute for this scope is better so that people can specify a starting day as they prefer...

**Comment by b3ndr** [comment]
Yes, it was my mistake - I offered pull request without testing my changes. So, this way works much better, you can test it and specify starting day of the week

**Comment by 45kb** [comment]
@b3ndr Hi, thank you now looks better :)

Just one thing we don't understand:

here you have the attributes https://github.com/b3ndr/angular-datepicker/blob/master/src/js/angular-datepicker.js#L13

Why you define this here? : https://github.com/b3ndr/angular-datepicker/commit/fc8b0b918a58808bd345206ac9a78feca03802dd#diff-25beb811844343dc768ce59e4b1ffaf1R44

Also could be great to update README in such cases :+1: 

Let know so that we can test and merge if everythings ok :100:

**Comment by wouldgo** [comment]
@45kb got the point :dart:

**Comment by nuragic** [comment]
Hi! Any progress about this one? Thanks!

**Comment by davidsandoz** [comment]
Now that #198 is merged, you can use the option `date-week-start-day` to change the first day of the week.

**Pull request closed without merging**
