### PR TITLE
Issue #209

### PR DESCRIPTION
**Pull request by lucas3003**

### CODE REVIEW

**Comment by 45kb** [comment]
@lucas3003 awesome, PR is correct, does this fixs the problem? you tried replicating the problem ?

thanks

**Comment by lucas3003** [comment]
It worked on the project I tested. It would be better if @pdamidi , who opened the issue, could test.

**Comment by 45kb** [comment]
@lucas3003 i alerted him, will wait some time and in case merge it anyway.

Just please pull your fork and commit again i made some commit :)
Always run the linter don't forget about that, thanks :)

**Comment by 45kb** [comment]
closes #209

**Pull request merged**
