### PR TITLE
Add option to disable weekdays

### PR DESCRIPTION
**Pull request by fabianoroberto**
I'll use option `date-disabled-weekdays="[2,3,4,5,6,0]"` to allow select only mondays of calendar

### CODE REVIEW

**Comment by 45kb** [comment]
@fabianoroberto This looks awesome, thanks for your time. Can you please revert `dist/` files and commit so i can merge it ?

thanks a lot.

**Comment by fabianoroberto** [comment]
@45kb done!

**Comment by 45kb** [comment]
thanks a lot going to released this in v2.1.19 👍

**Comment by 45kb** [comment]
released v2.1.19

**Pull request merged**
