### PR TITLE
Fix mobile year selection issue #201

### PR DESCRIPTION
**Pull request by tipycalFlow**

### CODE REVIEW

**Comment by 45kb** [comment]
@tipycalFlow thanks! hae  you checked if years selection is ok on no-mobile too?

**Comment by tipycalFlow** [comment]
Works the same on chrome for mac. Might need to check on other browsers.

**Comment by 45kb** [comment]
@tipycalFlow great! yes try please at least safari, firefox and IE 10/11 if you have them.

Then i'll merge this, let me know i am here don't worry :)

**Comment by tipycalFlow** [comment]
Tested with safari iOS 10, safari, firefox, IE 11&10 (user-agents from safari's `develop` menu). I have a mac machine so won't be able to test on windows.

**Comment by 45kb** [comment]
@tipycalFlow awesome, it's enough,  the js is angular so will run everywhere hopefully.

Going to merge and release this.

**Comment by 45kb** [comment]
shipped in new 2.1.10 thanks @tipycalFlow 👍

**Pull request merged**
