### PR TITLE
PR Additional update for issue #131

### PR DESCRIPTION
**Pull request by hsiri**
- Issue #131 Datepicker not hiding in focus out

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @hsiri , the only problem with this, is that, if you try navigating the calendar using Tab key, you'll see it doesn't work. (At least on Chrome)

I am afraid this could not be merged atm.

**Comment by hsiri** [comment]
@45kb thanks for the comment. i have a question. i tried using Tab key(without the codes i have changed), it won't also work on Chrome. is it okay on your side?

**Comment by 45kb** [comment]
Yes it seems to work on chrome, maybe a better check will be needed, but that's the only reason why we can't hide it that way, many people prefer tab keys over mouse, i think you will understand.

So could be great to fix the tab navigation first ;)

**Comment by hsiri** [comment]
hello @45kb, i've created a sample using my code above http://plnkr.co/edit/edqXLufCOS1y5rVIO6cK?p=preview (this is basing on tomecko's code for #131), the tab just works okay

**Comment by 45kb** [comment]
Unfortunately it doesn't, here i am on a Mac with latest Chrome version, where are you testing it?

If i tab 2 times it doesn't enter the calendar but it switch to the second input.

**Comment by hsiri** [comment]
i am also testing on Mac with latest chrome version. haha. this is becoming weird

**Comment by hsiri** [comment]
hello. how is this going? tab still won't work?

**Comment by 45kb** [comment]
@hsiri  Hi, sorry for the delay but these are busy days.

The tab key must be used to navigate the datepicker so first that must work on major browser (fix tab navigation) then we could add an attribute option to turn it off, so that if you want to pass from an input to another via tab key, it will be possible.

At the moment both, tab navigation need to be fixed for all the browsers, it seems to work only for chrome. Tab attribute option need to be done.

**Pull request closed without merging**
