### PR TITLE
added asCalendar attr

### PR DESCRIPTION
**Pull request by coolbombom**
The datepicker can be used as an actual calendar. The code is checking for the attr asCalendar and if that exists then it don't hide the datepicker when clicking anything, but keeps it open for use as an calandar, im using this in my code tweeking the look of the datepicker with css. then it is up to the user if they wan't to hide the input element or not!

### CODE REVIEW

**Comment by 45kb** [comment]
@coolbombom Hi, thanks for your fantastic work, can i test this new feature somewhere? Maybe your own fork? :+1:

**Comment by coolbombom** [comment]
@45kb Hi, here is an example - http://plnkr.co/edit/AEt4GcYojAfT9XUJkdZL?p=preview

All it does, is to keep the datepicker open all the time!

cheers
c_bb

**Comment by 45kb** [comment]
@coolbombom Hi, sorry for the delay, actually i really think this could be achieved by just using CSS.

For example : 

```<datepicker datepicker-toggle="false"><input/></datepicker>```

Then we can just put this in the CSS file: 

```datepicker[datepicker-toggle="false"]{  
 visibility:visible;
}```

And it should work fine, don't you think?

**Comment by 45kb** [comment]
Ok definitely thanks so much, i released a new version and the ```datepicker-toggle="false"``` should do this for you!

https://github.com/720kb/angular-datepicker/releases/tag/0.2.17-beta

**Pull request closed without merging**
