### PR TITLE
Added automatic date selection when date is typed in field. Fixed issue with calendar not disappearing when input field loses focus.

### PR DESCRIPTION
**Pull request by andyepx**

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @andyepx , thanks for the fantastic work!

Just all this has to be optional to be merged, so with a new attribute that i can choose to turn off and on ( date-live="true || false")

Have you tried using this feature togheter with with ```date-min-limit=""``` and or ```date-max-limit=""``` ?
What happens if i write a non-selectable date, how you handle this?

Thank you, let know as soon as you can please :+1:

**Comment by andyepx** [comment]
Hey @45kb - I will look into having a toggle for what I added. I haven't used date-min-limit and max-limit as they are not necessary for what I have used the plugin for... I will make sure it won't break and send you a new pull request as soon as those changes are done :)

Thank you!

**Comment by 45kb** [comment]
@andyepx Hi, thank you a lot, this feature is awesome and needed.

Just remember to make it option like using the new attribute date-live="true or false"  and we will merge and release it :+1:

**Comment by 45kb** [comment]
Closing, but we appreciated a lot your suggestion! :+1: 

Now it is possible to enable `date-typer=""`

**Pull request closed without merging**
