### PR TITLE
fix invalid date on mobile

### LINKED ISSUE #262: datepicker is having issues with angular 1.6.x
Angular datepicker is having issues with angular versions 1.6.x ,I have tested with older versions it was working fine . Check the below ss for reference . Please fix the issue asap

With Version 1.6.x

image

With version earlier to 1.6.x

image

I hope the above ss will help

### PR DESCRIPTION
**Pull request by udaraweerasinghege**
The ng-change hook on mobile https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L33 is hit initially with a value of null which makes monthNumber undefined.

Fixes : https://github.com/720kb/angular-datepicker/issues/262

### CODE REVIEW

**Review by ericjim — APPROVED** [review]

**Comment by udaraweerasinghege** [comment]
@45kb pls :)

**Review by PizzaPete — APPROVED** [review]

**Review by TQx8 — APPROVED** [review]

**Review by Wvduijn — APPROVED** [review]
Seal of approval 🥇

**Review by petervanmanen — APPROVED** [review]

**Comment by cabello** [comment]
Any chance we can get a second set of eye on this PR? :)

**Comment by f-anthonioz** [comment]
Hello there, I just checked the PR, and besides removing some trailing white spaces, the changes consist in a simple guard clause added to that selectedMonthHandle hook.

Any idea when this could get merged ? (I just need to know if I have to fork the repo in the meantime).

Thanks for your time !

**Comment by sulphur** [comment]
any chance to merge it ?

**Comment by marcoshmendes** [comment]
I've tested and it works like a charm. Like @f-anthonioz said, all that it need is removing some trailing white spaces. I bet a lot of people has problems with this issue. Merge please.

**Comment by udaraweerasinghege** [comment]
The repo hasn't been updated since 2017. We ended up forking the library with this fix to maintain it. I'd recommend doing the same if you want to continue using this package.

**Comment by udaraweerasinghege** [comment]
I'm closing this PR since I don't think this'll be merged in. If you stumble upon this thread, you'll need to fork and fix it, or use an existing more up to date fork.

**Pull request closed without merging**
