### PR TITLE
Added title attributes to controls to meet WCAG2AAA accessability requirements

### PR DESCRIPTION
**Pull request by FeminismIsAwesome**

### CODE REVIEW

**Comment by wouldgo** [comment]
Hi @FeminismIsAwesome,

thanks for your contribution in adding the titles attributes for the elements. Only a thing: could you please add some documentation in the README.md file just to let know that these params are present explaining what they do?

Thanks
Dario

**Comment by FeminismIsAwesome** [comment]
No problem! Should I link to the WCAG2AAA guidelines to explain or just saying what they do should be enough?

**Comment by wouldgo** [comment]
just saying that those new attributes are present is enough (it's just a reference for the directive users).

**Comment by FeminismIsAwesome** [comment]
Is that the level of detail you're looking the readme?

**Comment by wouldgo** [comment]
Good. Merging it.
Again thank you for your time helping us.

**Pull request merged**
