### PR TITLE
Revert "Extending logic to set month and year"

### PR DESCRIPTION
**Pull request by 45kb**
Reverts 720kb/angular-datepicker#234

@tipycalFlow reverting due to this issue https://github.com/720kb/angular-datepicker/issues/237

### CODE REVIEW

**Comment by tipycalFlow** [comment]
@45kb I think the problem with #237 was because the date was not being parsed for a particular format. Reverting will fix the problem but issues #235 & #226 will need to be reopened and we need to find a better way to populate the selected month, year and day as selected when the datepicker is opened. Could you please look into it and find a way to fix them?

**Comment by 45kb** [comment]
@tipycalFlow i will try to take a look as soon as possible 👍  thanks, i re-opened the issues

**Comment by tipycalFlow** [comment]
@45kb this is only for first time datepicker show though and we also need to test this for multiple datepickers on a single page.

**Comment by 45kb** [comment]
@tipycalFlow yeah, i am wondering how this bug was introduced since it always worked perfectly, really weird, seems like something is running long task or looping before to show the active class :/

**Pull request merged**
