### PR TITLE
Fallback fonts for Windows users

### PR DESCRIPTION
**Pull request by Codesleuth**
We see the datepicker as the following on Chrome 51.0.2704.103 for Windows 10.

image
image

To fix this we've added Arial and sans-serif to the font list, and swapped the up arrow to the opposite of the existing down arrow.

image

image

### CODE REVIEW

**Comment by 45kb** [comment]
Hi @Codesleuth  thank you for the PR, i will have a quick look later and release a new version when merged, thanks a lot 👍

**Comment by 45kb** [comment]
Ok, @Codesleuth  at the moment it is not possible to merge this https://github.com/720kb/angular-datepicker/pull/189/files#diff-26511aed466ccdaa66feffffc0a3c994R85

I will merge everything about the font but that arrow look very ugly for the moment

I will try to find a better solution or if you have some idea let me know please.

Thanks

**Comment by Codesleuth** [comment]
If you like the down arrow but not the up arrow (which should look the same since they are a pair) perhaps it could be css rotated instead?

Unfortunately I don't have a Mac to preview it, so I'm not sure what it looks like for you.

**Comment by 45kb** [comment]
@codeocelot rotation could be a great solution, if it's supported on IE 9 + it is ok.

Atm it looks like a streched arrow as you can see

schermata 2016-06-22 alle 17 57 38

**Comment by 45kb** [comment]
Ok we can rotate it http://caniuse.com/#search=transform 👍 

I will release a new version asap.

For mobile browsers such as Opera mini it is not needed, since selectboxes will appear for that.

**Comment by 45kb** [comment]
📦  Shipped in here https://github.com/720kb/angular-datepicker/releases/tag/2.1.6

Should work now, let me know if you try it 👍 

Thank you a lot.

**Pull request merged**
