### PR TITLE
Add option to change first day of week

### PR DESCRIPTION
**Pull request by davidsandoz**
This relates to #30.

Adding a directive attribute that let us choose which day of the week we want as the first day of the week by giving its numeric value (0 to 6).

### CODE REVIEW

**Comment by 45kb** [comment]
hi there, thanks for your time and sorry for delay, do you have a repository or a fork where i cn test your code?

thank you.

**Comment by davidsandoz** [comment]
Thanks for your reply.

Yes, I forked in https://github.com/davidsandoz/angular-datepicker and worked in the branch `first-day-of-week`

No, I didn't try it with different browser locals. Do you have a specific way to test that?

**Comment by 45kb** [comment]
@davidsandoz  i will try the changes, to change locale of your browser just change your timezone on your OS, if your Os points to UK change it to Brasil and so on, the browser will detect your timezone and locale by the OS

**Comment by davidsandoz** [comment]
Hi @45kb, did you had time to try the changes?

**Comment by 45kb** [comment]
Hi @davidsandoz unfortunately had really no time, what baout you, you got any chance to try with different locales?

**Comment by 45kb** [comment]
Ok @davidsandoz  i tried it but it seems is not working, tell me if i am doing it correctly:

1) cloned your fork: https://github.com/davidsandoz/angular-datepicker
2) added date-week-start-day="3" here https://github.com/davidsandoz/angular-datepicker/blob/master/index.html#L22
3) open datepicker but starting day of the week is still Sunday

Am i missing something?

**Comment by davidsandoz** [comment]
@45kb My changes are in the branch `first-day-of-week`. Checkout the branch and try there, it should work 🙂

**Comment by 45kb** [comment]
It works @davidsandoz thanks for explanation, and for your time!

**Comment by davidsandoz** [comment]
Thanks, awesome!

**Pull request merged**
